miraz_user_homepage:
    pattern:  /
    defaults: { _controller: MirazUserBundle:Default:index }

miraz_user_show:
    pattern:  /user
    defaults: { _controller: MirazUserBundle:Default:show }

miraz_user_about:
    pattern:  /about
    defaults: { _controller: MirazUserBundle:Default:about }

miraz_user_register:
    pattern:  /register
    defaults: { _controller: MirazUserBundle:Default:register }