parameters:
#    miraz_user.example.class: Miraz\UserBundle\Example

services:
#    miraz_user.example:
#        class: %miraz_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
